### ISSUE TITLE
Difference between oss and extra still unclear

### ISSUE THREAD

**Issue by Offerel** [SkyTubeTeam/SkyTube#1035]
I have read the description that the extra version has some features which are not available in the oss version, but it's unclear at least for me, what exactly that means. What advantage has the extra version in detail?

**Comment by JFMugen** [comment]
+1 

I am not sure what "Official YouTube player support" means tbh.

**Comment by ff1992ff** [comment]
To my knowledge OSS only uses Open source code and therefore the unofficial Skytube video player - the extra version also supports the official YouTube player. When YouTube changes something at the backend, the SkyTube player has to be adjusted in order to properly function, while the official YouTube player always should work. However, the official YouTube player is quite limited in its function compared to the SkyTube player.

You can test the different players when you have the Extra version by going to:
settings / videoplayer / default | legacy  (unsupported) | official

**Comment by JFMugen** [comment]
> To my knowledge OSS only uses Open source code and therefore the unofficial Skytube video player - the extra version also supports the official YouTube player. When YouTube changes something at the backend, the SkyTube player has to be adjusted in order to properly function, while the official YouTube player always should work. However, the official YouTube player is quite limited in its function compared to the SkyTube player.

May I ask what "Youtube Player" is? I mean it sounds like it uses Youtube App, which doesn't make sense?

**Comment by ff1992ff** [comment]
Official YouTube Player:
![Screenshot_20220316-211815533](https://user-images.githubusercontent.com/61371707/158683148-3ca10061-3be6-4264-adb5-836cc1d230cb.jpg)

SkyTube Player:
![Screenshot_20220316-211947905](https://user-images.githubusercontent.com/61371707/158683428-b9c351f5-13c9-4ca8-bf5f-7f52a7e87c64.jpg)

Official YouTube player is similar to how YouTube is displayed in your web browser. I have attached two images of the same video in order for you to see the different GUIs. 

Normally while playing a video with the SkyTube player there is no border and android control buttons, but it appeared here because of my screenshot. I hope this helps you!

**Comment by JFMugen** [comment]
@ff1992ff It definitely does. Thank you :)

**Comment by Offerel** [comment]
Ahhh okay. So besides this mentioned play functionality, the rest of the application seems to be identical. Ok got it. Many thx.

BTW: i have enabled the YouTube player now to test it. But for every video i tried, the application crashed. If I change the player back to SkyTube, the same video plays fine without issues. The only difference at least for me was, the video seems to be a little bit smaller with SkyTube api, compared to YouTube. But I couldn't get past the thumbnail without crashing the app. 

I don't know if I have accidentally set some wrong settings. Found this only by testing the functionality.

**Comment by gzsombor** [comment]
Apart from that Youtube Player component, Extra has Google Chromecast support (this feature needs some proprietary Google code, so it can't be part of the OSS version. But that's all the differences.
