### ISSUE TITLE
Return Dislike Counter

### ISSUE THREAD

**Issue by ff1992ff** [SkyTubeTeam/SkyTube#1059]
Hey everyone! I just installed the updated version of SkyTube and think that the addition of the sponsor block functionality provides great value to the individual user. This addition has given me an idea of another feature, that should be added:

I, as many other users, miss the stats for dislike information on YouTube videos. I know, that this value was only hidden to the public recently and could be still requested with the YouTube API. However, they changed that too and now this number isn't accessible to anyone, but the channel owner and YouTube themselves. From the browser extension community there have been attempts in reviving this feature by applying an calculated approximation of the probable dislike count through computation of the dislike ratio of their user base with regards to a specific video, the view count and the like count... A return of this feature to SkyTube would be really great! Thank you!

Kind regards,
Frank

**Comment by drogga** [comment]
@gzsombor
I think that this can (should) be closed now...

BTW, there's only "Extra" builds for the latest 2 releases, there are no "Oss" builds (only Snapshots), I explained this better in the discussion for v2.983, please check.

**Comment by drogga** [comment]
@gzsombor
I think that this can (should) be closed now...

BTW, there are only "Extra" builds for the latest 2 releases of the 2 repos, there are no "Oss" builds (only Snapshots), I explained this better in the discussion for v2.983, please check.

**Comment by drogga** [comment]
@ff1992ff, @gzsombor
I think that this can and should be closed now, since it's implemented already.

**Comment by drogga** [comment]
@ff1992ff, @gzsombor
I think that this can and should be closed now, since it's implemented already and a few others too, also @gzsombor, @ram-on or some other with permissions can give me rights \ permission, by inviting me to be a member, collaborator or whatever, so I can close those when I can and have time...

**Comment by drogga** [comment]
Let's try again, I'm reposting this comment for a third time, untill someone sees it and do something about.

@ff1992ff, @gzsombor
I think that this can and should be closed now, since it's implemented already and a few others too, also @gzsombor, @ram-on or some other with permissions can give me rights \ permission, by inviting me to be a member, collaborator or whatever, so I can close those when I can and have time...

**Comment by gzsombor** [comment]
Yes, thanks, I think this was released in [2.982](https://github.com/SkyTubeTeam/SkyTube/releases/tag/v2.982)
