### ISSUE TITLE
Skytube detects new videos that do not seem to exist

### ISSUE THREAD

**Issue by zqysurj** [SkyTubeTeam/SkyTube#1124]
**Describe the bug**
Database is altered when you download then read a short 

**To Reproduce**
  1. Use a profile already subscribed to channels with unread shorts
  2. Save and reload database to force channel updates
  3. Download a "short"
  4. Play the downloaded video in skytube
  5. Save and reload database to force channel updates
  6. Skytube tells "xx new videos" but did not add any videos to the list. This number grows +1 for each video that followed steps 2&3

Steps 2&3 corrupt "Channel_Id" in "subscription_videos" in subs.db

**Expected behavior**
Skytube should not find new videos if I reupdate videos and no new videos have been posted 

**Setup:**
 - Android version: 10
 - Is Your device rooted? No
 - Do You use Tor or any VPN service with your device? no
 - App source [e.g. FDroid, Downloaded from GitHub, self build] : Github or FDroid
 - App Version [e.g. v2.977] : latest (2.986)
 - App Flavour [e.g. Extra or OSS] Extra

**Comment by hamishmb** [comment]
Yeah, it's doing this for me as well, it always says 5 new videos when there aren't any, but the number isn't increasing over time.

To Reproduce
Steps to reproduce the behavior:

    Add a lot of channels
    Use the app for a few days
    Update videos
    Directly re-update videos
    Skytube tells "xx new videos" but did not add any videos to the list. This number grows over the weeks

Expected behavior
Skytube should not find new videos if I reupdate videos

Screenshots
TODO - will provide later.

Setup:

    Android version: 11
    Is Your device rooted? No
    Do You use Tor or any VPN service with your device? no
    App source [e.g. FDroid, Downloaded from GitHub, self build] : F-Droid
    App Version [e.g. v2.977] : latest (2.984)
    App Flavour [e.g. Extra or OSS] unknown, probably OSS as it's from F-Droid?

Additional context
This strange behaviour started some versions ago - had it for a few months.

**Comment by malloy139** [comment]
I can confirm this

**Comment by navid-zamani** [comment]
@zqysurj: I just looked in my exported `*.sqlite` file, and no table in no database in there contains any URL in front of any `Channel_Id` field value. So I figure that can’t be the cause.

Also, the current refresh did not find a new video, even though I *just* found and downloaded it with yt-dlp (using the channel /videos page URL amd yt-dlp’s feature of remembering which videos it already knows. So some videos don’t get downloaded too?

I wonder: Why does SkyTube not just use yt-dlp? Or its code? It’s open source and much more advanced, with metric tons of functions and supported sites.

**Comment by zqysurj** [comment]
> @zqysurj: I just looked in my exported `*.sqlite` file, and no table in no database in there contains any URL in front of any `Channel_Id` field value. So I figure that can’t be the cause.

I tested once again with an old file in "Db Browser" : using search and replace to delete "https://www.youtube.com/channel/" inside the "subscription_videos" table contained in "subs.db"

It did the trick, I just dropped from 170 ghost videos to zero

**Comment by drogga** [comment]
I think this anomaly happens when the owners of a channel we are subscribed to unpublishes \ deletes a video, because it happened recently (a few weeks ago) to me too and now my `X new videos from subscribed channels` number is always incorrect (it shows a toast msg. for +1 more on every fetch), the culprit I think was Austin Evans, when he deleted a video titled `PS5 Pro` and it seems like unsubscribing and subscribing again didn't helped and the only way to fix this is probably to chean the SkyTube's data and manually set it up with my preferences and subscribe to all of the 31 channels I'm currently monitoring, one-by-one, because I believe that if I backup and restore the issue\problem will continue to occur.

_The culprit might also be "ETA PRIME", because he's constantly changing video's Titles and Thumbnails, because it seems like the guy is chaotic and can't set his mind on those 2 and tends to change them after the videos are being uploaded \ made "Public"._

**Comment by drogga** [comment]
^ @gzsombor ^ take a look at this please and maybe add the `help wanted` label\tag, since you're no longer interested in this project, or simply don't have time to deal with it, if that's the case, then I hope that you will eventually find some time to work on this and soon, instead of let it die, because only force-updating the NPE every 2 months or so, or when there's a critical error preventing the app from playback, simply isn't enough and there are issues that can't be magically auto-resolved by it, so we can't rely on this and others being fixed by themselves.

**Comment by zqysurj** [comment]
@gzsombor, I now have a reliable way to reproduce the bug + details of how database is affected, see first post for more details. If I can be of any help to solve the bug, Do not hesitate to contact me

**Comment by zqysurj** [comment]
Bug has been solved by version 2.988

**Comment by zqysurj** [comment]
Bug has been solved by version 2.988

**Comment by gzsombor** [comment]
Thanks for confirming, that this is solved now!
