### ISSUE TITLE
Make download location of videos customizable

### ISSUE THREAD

**Issue by RandomModderJDK** [SkyTubeTeam/SkyTube#1190]
**Is your feature request related to a problem? Please describe.**
Right now all my videos from different apps are stored in the /storage/emulated/0/Movies folder. This is a big a** pile of videos, which is really confusing.

**Describe the solution you'd like**
Make the download path customizable, so everyone can decide what their data folder should be. The default would still be, the current path. This solution is great for those who do not like the current path.

**Describe alternatives you've considered**
Just change the hardcoded path for downloads to Movies/Skytube for example, for better organization. This is problematic, because if you would upgrade, then you would need to manually move previous downloads. 

**Additional context**

**Comment by gzsombor** [comment]
There is already a setting for that, under "Network and Downloads" -> "Video Download Folder"
Unfortunately, there were changes between the Android version, what storage are readable/writable by the apps, and it is a bit more problematic in SkyTube, because it uses the system downloader service, so there could be setups, where Skytube could read the file, however the downloader cant write there, or vice-verse.
 There is a newer API, which can be used for file handling, and also, having a better/internal downloader service would help a lot.
