### ISSUE TITLE
V2.991 extra showing incorrect subscription state

### ISSUE THREAD

**Issue by dagofr01** [SkyTubeTeam/SkyTube#1312]
Entering a subscribed channel did not show the channel as subscribed and showed a subscribe button (even though in german in my case). Deleting the cache did not really help even though it may have changed the behavior for a particular example. I did not yet try finding a certain pattern where it fails for the moment yet.

**Comment by drogga** [comment]
That's what happens when @gzsombor doesn't properly test the changes before pushing them as an update, to make sure that everything works...
For instance: The new subscribe/unsubscribe is aweful, huge, up top and it hides behind it 3 other buttons - why !?, who needed this ?, it was good as it was, not being such an annoyance and "in the eyes", also the search query text is now unnecessarily larger (not while typing/editing), sure there is a need for touching a few things here an there in the UI for a better UX, but that's not it and there are way, way bigger issues with playing and discovering content that should've addressed first, before going for the UI...

@gzsombor **Please bring back the old sub/unsub button**.

**Comment by drogga** [comment]
@gzsombor
I didn't wrote that it's a bug, but just aweful, for me on many devices with small & large, but mostly small screens it was never an issue pressing it, it was also where it should've been placed, not getting in the way, the one in the derails sheet is fine, but the one in the chamnels is disgustingly aweful, the app is still basically unusable without a mouse on ATV, I just tested it with a KB and you can't even go back/forward with the arrow keys, nor play/pause with the spacebar, the same will be with a remote (D-Pad).

**Comment by drogga** [comment]
@gzsombor
I didn't wrote that it's a bug, but just aweful, for me on many devices with small & large, but mostly small screens it was never an issue pressing it, it was also where it should've been placed, not getting in the way, the one in the details sheet is fine, but the one in the chamnels is disgustingly aweful, the app is still basically unusable without a mouse on ATV, I just tested it with a KB and you can't even go back/forward with the arrow keys, nor play/pause with the spacebar, the same will be with a remote (D-Pad).

How do I use the buttons that are now behind that new misunderstatement of a button ?
