### ISSUE TITLE
Why SkyTube idea

### ISSUE THREAD

**Issue by Palivec** [SkyTubeTeam/SkyTube#408]
Hi,
the reason why I use SkyTube is that I can play music videos with the display off, so I save lot of battery power. I believe I'm not alone. Put it in the "Why SkyTube" section, more people will use it !

**Comment by kgbm3** [comment]
It's a wonderful piece of software, plus a great implementation (and execution)! :) 

Recently, I've been "suspended" off of YouTube - twice! First they had reinstated my account (fairly quickly, maybe within a week or so) and then I got shut off again. No replies to my appeals, except for one email where they've told me NOT to write again, as only the first one is to be considered... 

I've been "online" since before 2400-baud modems used to cost a fortune, during the BBS era and while IRC was -still- working over Telnet - and, never been "banned" from anywhere, let alone YouTube, meh. 

So, there's no way for me to find out WHY they're denying me access and - since the account is tied to the phone and YouTube -clearly- states that they don't allow multiple accounts... There is no alternative. :/ 

Except, in comes SKYTUBE to save the day. I mean, how could I ever thank the devs. Can't send them a $1M myself, but **will** contribute, what I can; pretty sure how each, individual, contribution can be (crucially) important! =) 

Alright, thanks for bearing with me!! Peace! ☮️

**Comment by gzsombor** [comment]
Thanks for the comment and for praise!
