### ISSUE TITLE
Responses to sideswipes are often slow.

### ISSUE THREAD

**Issue by kdsdata** [SkyTubeTeam/SkyTube#940]
Release: free.rm.skytube.oss_37.apk

Responses (start of video at new location) to sideswipes is often slow. Sometimes the video does not auto-continue after a sideswipe.  Both conditions are intermittent.

**Comment by kdsdata** [comment]
Perhaps this [SkyTube/issues/933#](https://github.com/SkyTubeTeam/SkyTube/issues/933#issuecomment-802940829) is related.

**Comment by gzsombor** [comment]
Seeking in the video could be slow - especially if you are playing from the network, because - AFAIK - SkyTube doesn't use DASH or HLS. I think, this shouldn't be too difficult to add, as ExoPlayer supports both, and NewPipeExtractor I think returns these type of streams as well, but honestly, I haven't diged deep into this, so maybe, it's hard, or maybe, even with DASH/HLS seeking wont be much faster. :confused: 
 I hope, I haven't misunderstood your issue.

**Comment by drogga** [comment]
ST uses Dash (HLS) on every resolution greater than 720p, else it would've been without audio !
...I already mentioned this at least once in my comments...

**Comment by kdsdata** [comment]
If there is a solution, you guys are the ones to know.  The problem is certainly network related.  For me, I have found a reasonable work around.  If it seems it's a video I want to watch (I watch long train cab ride videos), and it seems I may want to jump back and forth, I just go out first, select to download, and do something else for a few minutes, like analyze the same for another video.  Then, going back in to the downloaded video, selecting any location is so fast that there is no reason for complaint.

**Comment by drogga** [comment]
@gzsombor - SkyTube uses Dash (HLS) on every resolution greater than 720p !, else videos would've been without audio...
_...I already mentioned this at least once in my comments..._

**Comment by kdsdata** [comment]
I am satisfied that downloading the video fixes this issue.  I am closing this topic.

**Comment by gzsombor** [comment]
Thanks @kdsdata for the follow up!
