### ISSUE TITLE
Default player unable to play video

### ISSUE THREAD

**Issue by n-buna404** [SkyTubeTeam/SkyTube#959]
**Describe the bug**
Default player unable to play video

**To Reproduce**
1. Go to Skytube extra
2. Click on any video. With default player
3. Watch the video playing without sounds and images

**Expected behavior**
Watch the video playing with sounds and images
.

**Screenshots**
If applicable, add screenshots to help explain your problem, or the link for the video, where You've found the issue

**Setup:**
 - Android version: [4.1.2] Samsung GT-P5100
 - Is Your device rooted? No
 - Do You use Tor or any VPN service with your device? No
 - App source [e.g. FDroid, Downloaded from GitHub, self build] Github
 - App Version [e.g. v2.977] latest 2.978
 - App Flavour [e.g. Extra or OSS] Extra

**Additional context**
It was strange that legacy player were able to play the video but not default player. Currently using legacy player. It was found only starting 2.978

**Comment by gzsombor** [comment]
I think, the problem is that SkyTube thinks, that the default player could playback more stream types - and picks one, where the audio is not supported by the OS/Hardware. With the legacy player, it just picks an MPEG stream, I believe.

**Comment by drogga** [comment]
@n-buna404 - Same problem, that's why now I use v2.977 "Oss", it's not that bad in it as in v2.978, you have to set the min. rez. to 240p and max. to 720p and constantly change the "Video Quality Selection" (Network and Downloads>Video Resolution) between "Least Bandwith" and "Best Quality" for those that won't play in HD, because it appears that the "Legacy" uses only regular streams, but the "Default" ("new") one prefers .DASH (WebM) streams with separate audio, but those can only be played with audio only on 5.0 and up (in some cases maybe in 4.4 too).

Keep in mind that the SkyTube's own exported subscription DB backups are not backward compatible, you cannot do a backup in v2.978 and import it on v2.977 or older, the same with the app (.apk) versions installs -> not down-gradable, even if you have root and patches or modules that usually allow you do install older version over a newer's, this app will crash, so forget about it.

**Comment by n-buna404** [comment]
Closed this since it was fixed in 2.979. Been testing for a month or so and did not need to fall back to legacy player again.
